logo: ./logo.png
description: > 
  Engineering student focusing on Acoustics and Audio Engineering with a demonstrated history of research-based work in spatial audio processing, 
  Head-Related Transfer Function (HRTF) and Machine Learning on the audio signal. 
  <br><br>
  Skilled in Python, MATLAB, Unity3D, Acoustical Measurement, TensorFlow. Interested in Machine Learning and Data Analysis. 
  <br><br>
  <a href='https://www.linkedin.com/in/mingyang-lee-a5019199/'>View My linkedin Profile</a>

theme: jekyll-theme-minimal
